#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;"
/etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
service nginx start"'"
service nginx start
