#!/usr/bin/env bash
# fizzbuzz problem
i=0
while [ $((i++)) -lt 100 ]; do
	if [ $((i % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $i
	fi
done
