#!/usr/bin/env bash
# This script is displaying "luck stuff" 10 times
i=0
while [ $((++i)) -le 10 ]; do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
fi
done
