#!/usr/bin/env bash
# file information
file="holbertonschool"

if [ ! -e "$file" ]; then
	echo "$file" file does not exist
	exit 0
fi
echo "$file" file exists

if [ -s "$file" ]; then
	echo "$file" file is not empty
else
	echo "$file" file is empty
fi

if [ -f "$file" ]; then
	echo "$file" is a regular file
fi
