#!/usr/bin/env bash
# to change your home IP with hosts file
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2	localhost/g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
